import type { Metadata } from "next";
import "./globals.css";
import { geistSans } from "./ui/fonts";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className={`${geistSans.className} h-full antialiased`}>
         <body className="min-h-full flex flex-col">
            {children}

            <ToastContainer />
         </body>
      </html>
   );
}
