import type { Metadata } from "next";
import "../globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Header from "@/components/header";
import { getHomePage } from "@/lib/strapi";
import { geistSans } from "../ui/fonts";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   const strapiData = await getHomePage();

   const [heroSection] = strapiData.sections || [];
   const { link, secondaryLink } = heroSection;

   return (
      <div>
         <Header link={link} secondaryLink={secondaryLink} />
         <main className="px-8">{children}</main>

         <ToastContainer />
      </div>
   );
}
